const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  loadState: () => ipcRenderer.invoke('state:load'),
  saveState: (data) => ipcRenderer.invoke('state:save', data),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (data) => ipcRenderer.invoke('settings:save', data),
  chat: (messages) => ipcRenderer.invoke('chat:send', messages),
  getGreeting: () => ipcRenderer.invoke('greeting:get'),
  getProviderPresets: () => ipcRenderer.invoke('providers:get'),
  loadMemory: () => ipcRenderer.invoke('memory:load'),
  saveMemory: (data) => ipcRenderer.invoke('memory:save', data),
  clearMemory: () => ipcRenderer.invoke('memory:clear'),
  getGrowth: () => ipcRenderer.invoke('growth:get'),
  addExp: (amount) => ipcRenderer.invoke('growth:addExp', amount),
  movePet: (dx, dy) => ipcRenderer.invoke('pet:move', { dx, dy }),
  movePetTo: (x, y) => ipcRenderer.send('pet:moveTo', { x, y }),
  startPetDrag: () => ipcRenderer.send('pet:dragStart'),
  endPetDrag: () => ipcRenderer.send('pet:dragEnd'),
  moveChatTo: (x, y) => ipcRenderer.send('chat:moveTo', { x, y }),
  getPetBounds: () => ipcRenderer.invoke('pet:getBounds'),
  getPetBoundsSync: () => ipcRenderer.sendSync('pet:getBoundsSync'),
  getChatBounds: () => ipcRenderer.invoke('chat:getBounds'),
  setWindowSize: (width, height) => ipcRenderer.send('pet:setWindowSize', { width, height }),
  setClickThrough: (flag) => ipcRenderer.send('pet:setClickThrough', flag),
  notify: (title, body) => ipcRenderer.send('notify', { title, body }),
  toggleChat: () => ipcRenderer.send('chat:toggle'),
  closeChat: () => ipcRenderer.send('chat:close'),
  openAppearance: () => ipcRenderer.send('appearance:open'),
  closeAppearance: () => ipcRenderer.send('appearance:close'),
  getAppearance: () => ipcRenderer.invoke('appearance:get'),
  saveAppearance: (data) => ipcRenderer.invoke('appearance:save', data),
  openSettings: () => ipcRenderer.send('settings:open'),
  closeSettings: () => ipcRenderer.send('settings:close'),
  getAutoStart: () => ipcRenderer.invoke('autostart:get'),
  setAutoStart: (enabled) => ipcRenderer.invoke('autostart:set', enabled),
  getShutdownStatus: () => ipcRenderer.invoke('shutdown:getStatus'),
  scheduleShutdown: (cfg) => ipcRenderer.invoke('shutdown:schedule', cfg),
  cancelShutdown: () => ipcRenderer.invoke('shutdown:cancel'),
  close: () => ipcRenderer.send('pet:close'),
  onTrayAction: (cb) => ipcRenderer.on('tray:action', (e, action) => cb(action)),
  onPetDragEnd: (cb) => ipcRenderer.on('pet:dragEnd', () => cb()),
  onChatOpen: (cb) => ipcRenderer.on('chat:open', () => cb()),
  onSettingsChanged: (cb) => ipcRenderer.on('settings:changed', () => cb()),
  platform: process.platform,
});
